name: iOS CI

on:
  push:
    branches:
      - main
      - lirycs
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode_16.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Show available simulators
        run: xcrun simctl list devices

      - name: Build
        run: |
          xcodebuild build \
          -scheme PitchMVP \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

      - name: Test
        run: |
          xcodebuild test \
          -scheme PitchMVP \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'