name: iOS CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode_16.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild build \
          -scheme PitchMVP \
          CODE_SIGNING_ALLOWED=NO